- CHANGELOG.md
Updated CHANGELOG.md for GitHub releases. After this commit we can create the v1.2.0 release and have our administration up-to-date.
> Updated CHANGELOG.md for GitHub.

- .gitattributes
- CHANGELOG.md
Removes the files of external libraries in source detection.
See difference:
[![asciicast](https://asciinema.org/a/2thhhvjtSY07AxK6nMcWHhONf.svg)](https://asciinema.org/a/2thhhvjtSY07AxK6nMcWHhONf)
> Excludes generated source in language detection

- lwip/lwip-2.1.1/src/netif/ppp/eap.c
This is an automatically generated security fix for a vulnerability detected in your code which is a variant of [CVE-2020-8597](https://nvd.nist.gov/vuln/detail/CVE-2020-8597). 
You can read in more detail about this vulnerability in [CERT Advisory VU#782301](https://kb.cert.org/vuls/id/782301/).
The vulnerability occurs because, given that `vallen` was checked to be less than `len`, it can never be the case that `vallen >= len + sizeof(rhostname)`. Therefore, `rhostname` never gets trimmed and the `rhostname` array may overflow.
While this PR was generated for your project automatically, the supporting analysis was performed and verified by the [GitHub Security Lab](https://securitylab.github.com/). 
The original finding was reported by Ilja Van Sprundel from IOActive.
The proposed patch …
> [SECURITY] Prevent `rhostname` array overflow

- infra/util/MemoryRange.hpp
Especially `value_type` and `const_iterator` come handy when writing tests, because they allow gmock's ElementsAreArray matcher to be used with a MemoryRange.
> MemoryRange: add aliases by STL convention

- CMakeLists.txt
- hal/windows/UartWindows.hpp
For more information w.r.t. to the default initialization issue in UartWindows.hpp, see: https://godbolt.org/z/E7qGE375K
> fix for building using clang

- .devcontainer/devcontainer.json
- README.md
- infra/util/CMakeLists.txt
- infra/util/Compatibility.hpp
- infra/util/Observer.hpp
std::result_of has been deprecated in C++17 and removed in C++20. Replaced by std::invoke_result.
- Created Compatibility header to support C++11 and higher versions.
- Used Compatibility header in Observer.
> Closes #54: std::result_of deprecation

- infra/util/IntrusiveBinarySearchTree.hpp
> Fix missing cassert include in IntrusiveBinarySearchTree

- infra/timer/Timer.cpp
- infra/timer/Timer.hpp
TimerRepeating::Start would call NextTriggerChanged twice, once via `SetNextTriggerTime` and once via `SetDuration`.
The call to `SetNextTriggerTime` would result in the underlying timer implementation getting a request to schedule a trigger sooner than the actual duration.
This change solves that issue by removing the double call to `SetNextTriggerChanged` and changing the initial TimePoint value passed to `SetNextTriggerTime` to the correct duration
Fixes #75
> Solved TimerRepeating::Start calling NextTriggerChanged twice

- infra/util/IntrusiveForwardList.hpp
- infra/util/IntrusiveList.hpp
- infra/util/IntrusiveUnorderedSet.hpp
- services/ble/Gatt.cpp
- services/ble/Gatt.hpp
- services/cucumber/CucumberStepStorage.cpp
- services/cucumber/CucumberStepStorage.hpp
infra/util/IntrusiveList, IntrusiveForwardList, IntrusiveUnorderedSet: insertion and erase functions now take a non-const reference, avoiding temporaries to be inserted
> infra/util/IntrusiveList: insertion and erase functions now take a non-const reference

- .devcontainer/Dockerfile
- cmake/emil_docker_tools.cmake
When running outside of a devcontainer, but Docker is installed add the option to run additional tools directly on the host.
> cmake/emil_docker_tools.cmake: add support for host Docker tools

- .clang-format
- .github/workflows/ci.yml
- .github/workflows/static-analysis.yml
- .vscode/settings.json
- infra/syntax/Json.cpp
- services/network/NameResolverCache.cpp
- services/tracer/TracerAdapterPrintf.cpp
- sonar-project.properties
* Don't use build-wrapper but use the compilation database as scanner input
* Separate out the step to convert from different sources to Sonar input
> ci: update Sonar scanning procedure

- cmake/emil_xsltproc.cmake
Download dependencies of xsltproc (libxml2, iconv and zlib) for Windows hosts and add to PATH if necessary.
> build(cmake/emil_xsltproc.cmake): download dependencies of xsltproc

- .github/workflows/ci.yml
- .github/workflows/static-analysis.yml
The seanmiddleditch/gha-setup-ninja action has not yet moved from node12 to node16 as is recommended by GitHub (https://github.com/seanmiddleditch/gha-setup-ninja/issues/16). This gives unnecessary warnings in our build summaries.
Replace the usage of the action by installing ninja via the package manager.
> build: remove seanmiddleditch/gha-setup-ninja

- cmake/emil_test_helpers.cmake
amp-devcontainer has been updated to only supply clang-15. The mutation test function in embedded infra lib still relies on clang-12.
This update resolves this issue by dropping the `-12` when clang-15 is detected
> ci!: Replaced mull-ir-frontend-12 with mull-ir-frontend

- .github/workflows/ci.yml
- .github/workflows/documentation.yml
- .github/workflows/fuzzing-pr.yml
- .github/workflows/linting-formatting.yml
- .github/workflows/static-analysis.yml
This PR enables the merge_group trigger for relevant ci-tasks necessary to enable the merge queue feature.
> ci: enable merge queue

- sonar-project.properties
As per https://docs.sonarcloud.io/advanced-setup/languages/c-c-objective-c/#analysis-cache the server-side cache is now supported on SonarCloud. This change enables that cache by-default and removes an analysis warning in the web-ui.
> ci: enable sonarcloud server-side cache

- .github/dependabot.yml
- infra/util/Compatibility.hpp
Add a check if __has_cpp_attribute is available before using it; VS2017 does not seem to have this defined.
Closes #134
> fix: add check for availability of __has_cpp_attribute

- .github/workflows/release-please.yml
- .github/workflows/validate-pr.yml
Add a workflow that validates if pull-requests adhere to conventional commits. This is necessary for correct operation of the automated release workflow.
> ci: add workflow to check PR conventions

- .github/dependabot.yml
Our repository contains Dockefiles; make sure that they are kept up-to-date automatically.
> ci: add Docker package ecosystem to dependabot

- .github/workflows/release-please.yml
Always use bash shell to uniformly resolve the path to the asset
> ci: fix release asset upload for Windows host

- .github/workflows/ci.yml
- CMakeLists.txt
Build a universal binaries supporting both x86_64 and arm64 architectures.
Set the minimum supported target version to 10.15.
> chore: create universal binaries for OS X (10.15 and higher)

- protobuf/echo_console/Main.cpp
cpp:S1044 Exception classes should be caught by reference
> ci: fix SonarQube finding cpp:S1044

- protobuf/protoc_echo_plugin_csharp/ProtoCEchoPluginCSharp.cpp
`.NET7.0` is now throwing a warning that all-lower case namespace are reserved
> chore: renamed `using pb` to `using Protobuf` for the csharp echo plugin

- .gitignore
- cmake/toolchain-x86_64-pc-windows-msvc.cmake
This PR adds support for cross-compilation from non-Windows hosts to Windows hosts.
It assumes the Windows SDK and CRT are installed at a path specified by WINDOWS_SDK_ROOT.
The recommended way of installing the SDK and CRT is by using xwin (https://github.com/Jake-Shadle/xwin):
`$ xwin --accept-license splat --preserve-ms-arch-notation`
xwin patches the SDK and CRT for case-sensitive filesystems; the --presere-ms-arch-notation is
necessary to make the /winsdkdir and /vctoolsdir options of clang work.
> build: add clang x86_64 Windows toolchain file

- CMakeLists.txt
- cmake/emil_xsltproc.cmake
The hacky way that PATH is extended with library has now been improved. There were still issues when building with Embedded Infralib as a dependency of other projects, which have now been solved.
> refactor: improve how PATH is set in custom commands

- protobuf/echo_console/CMakeLists.txt
- protobuf/protoc_echo_plugin/CMakeLists.txt
- protobuf/protoc_echo_plugin_csharp/CMakeLists.txt
- protobuf/protoc_echo_plugin_java/CMakeLists.txt
- upgrade/pack/UpgradeKeys.proto
- upgrade/security_key_generator/CMakeLists.txt
- upgrade/security_key_generator/MaterialGenerator.cpp
- upgrade/security_key_generator/MaterialGenerator.hpp
build: exclude protobuf tools and upgrade.security_key_generator from all unless emil is built standalone
> build: exclude protobuf tools and upgrade.security_key_generator

- infra/stream/InputStream.cpp
- infra/stream/InputStream.hpp
- infra/stream/OutputStream.cpp
- infra/stream/OutputStream.hpp
- infra/util/SharedPtr.hpp
- infra/util/WithStorage.hpp
- services/network/WebSocketClientConnectionObserver.cpp
- services/util/WritableConfiguration.hpp
ensure forwarding constructors have constraints that prevent copying / moving objects of the same type
> fix: ensure forwarding constructors have constraints

- protobuf/echo/protocol_buffer_echo.cmake
When the release-please Action creates a releasable PR the assets can't be downloaded from that release yet. This PR disables automatically updating the echo plugin version that is downloaded until a better solution is found.
> ci: don't auto-update echo plugin versions

- services/network/HttpClientBasic.cpp
- services/network/test/TestHttpClientBasic.cpp
This change is a one liner.
When Path is extracted, resulting BoundedString should have a internal range of size ;
- maxSize - hostUrlSize but previously it was maxSize - hostUrlSize*2
What was the issue?
- String range was also trimmed at the end, the size of the host url.
> fix: usable memory loss in HttpClientBasic::Path

- upgrade/pack_builder_instantiations/UpgradePackBuilderFacade.cpp
- This PR fixes the crash when ConnectionMbedTls is combined with UpgradePackBuilderFacade
1- Create ConnectionMbedTls
2- Run UpgradePackBuilderFacade 
3- Attempt to create ConnectionMbedTls for another host
4- Observe failure on `mbedtls_ssl_session_free()`
- When UpgradePackBuilderFacade is combined with ConnectionMbedTls, connection memory pool is allocated on the heap. However, UpgradePackBuilderFacade sets global mbed tls buffers on stack, which then causes free() to be called on heap pointers in the context of stack.
- When MBEDTLS_MEMORY_DEBUG is defined; `FATAL: mbedtls_free() outside of managed space` is printed. This indicates either the memory pool is corrupted or the pointers. In this case, mbedtls memory pool is set to stack memory while initialization of a ConnectionMbedTls …
> fix: UpgradePackBuilderFacade setting mbedtls global memory pool on stack

- services/network/NameResolverCache.cpp
cpp:S6232: Well-defined type-punning method should be used instead of a union-based one.
> refactor: fix Sonar findings

- services/ble/Gap.cpp
- services/ble/Gap.hpp
- services/ble/test/TestGapCentral.cpp
remove static functions from GapAdvertisingDataParser class
> chore: remove static functions from GapAdvertisingDataParser class

- .github/workflows/dependency-scanner.yml
The dependency-review-action can run only in PR context. Disable it for the merge queue.
Also remove the push event, the merge queue already runs in the context of main.
> ci: only run dependency-review on pull requests

- .vscode/settings.json
CMake Tools might not be configured to be shown on status bar in VSCode. (AFAIK this is due to A/B testing :) )
It would be make things easier if it's shown by default. 
For some, status bar might look something like this:
However, most of us use different targets and would want to switch with one click using the status bar.
After this change status bar should look like this:
> chore: enable compact status bar for CMake Tools by default

- lwip/lwip/CMakeLists.txt
Add sources for acd (Address Conflict Detection) to lwip target.
> fix: add acd sources to lwip

- .github/dependabot.yml
The Docker container for clusterfuzzlite is built and published automatically. This means a new daily pull request. Reduce the frequency of update to monthly.
> chore: reduce interval of clusterfuzzlite updates

- .devcontainer/devcontainer.json
- .github/workflows/static-analysis.yml
- CMakePresets.json
- cmake/emil_test_helpers.cmake
- external/crypto/mbedtls/CMakeLists.txt
Switch ci steps that conduct static analysis to amp-devcontainer to pin all the necessary dependencies. As opposed to running on the GitHub provided runner image with changing software specifications.
> chore: switch static analysis to container

- services/util/CMakeLists.txt
- services/util/SerialCommunicationLoopback.cpp
- services/util/SerialCommunicationLoopback.hpp
- services/util/test/CMakeLists.txt
- services/util/test/TestSerialCommunicationLoopback.cpp
Added SerialCommunicationLoopback that can be used to link together two classes depending on `hal::SerialCommuncation`. The SendData from server will send the data to the client's ReceiveData callback and vice versa.
The actual sending is scheduled via the EventDispatcher to mimick the asynchronous behaviour of a serial communication port.
> feat: added SerialCommunicationLoopback

- external/crypto/mbedtls/CMakeLists.txt
Added workaround by replacing CMAKE_C_COMPILER_ID with CMAKE_C_SIMULATE_ID when configuring mbedtls
> fix: added workaround mbedtls and clang-cl incomatibility

- .github/workflows/release-please.yml
Reverts philips-software/amp-embedded-infra-lib#494
The changes in this PR break our release build on main. It looks like the outputs of the release-please action are not properly propagated to the next workflow.
> Revert "build(deps): bump google-github-actions/release-please-action from 3.7.13 to 4.0.1"

- infra/stream/BufferingStreamReader.hpp
- infra/stream/InputStream.hpp
- infra/stream/OutputStream.hpp
- infra/util/Observer.hpp
- protobuf/echo/Echo.hpp
- protobuf/echo/test_doubles/EchoSingleLoopback.hpp
- services/network/ConnectionFactoryWithNameResolver.hpp
- services/network/WebSocketClientConnectionObserver.hpp
- sonar-project.properties
Implementing static analysis recommendations of adding virtual to destructors grew binary sizes of upstream projects.
> fix: remove virtual destructors reducing binary size

- external/crypto/mbedtls/CMakeLists.txt
- services/tracer/CMakeLists.txt
The current behaviour adds the defines to the assembler which is not compatible with how assemblers work with compile definitions
> feat: changed compile definitions to be compatible with the gnu assembler

- hal/generic/SynchronousUartGeneric.hpp
- Renamed SynchronousUartGeneric header guard to HAL_SYNCHRONOUS_UART_HOST_HPP
> fix: duplicate header guard HAL_UART_HOST_HPP

- infra/stream/BufferingStreamReader.cpp
- infra/stream/test/TestBufferingStreamReader.cpp
- protobuf/echo/Echo.cpp
- services/network/test/TestEchoOnConnection.cpp
- Fixed BufferingStreamReader accessing further then it should
- Offset reader in Echo correctly so the ECHO packets are parsed correctly.
> fix: BufferingStreamReader OOB access and Echo segments calculated correctly

- infra/timer/Timer.cpp
timer jumped from a timepoint to a new timepoint shall trigger calculation of next trigger time and notify the timerservice
> fix: timer jumped will trigger next trigger time update

- external/crypto/mbedtls/CMakeLists.txt
AppleClang has updated to Clang15. And since Clang15 there is a warning in mbedtls regarding a doxygen comment.
This pull request disables the documentation warning when compiling with AppleClang for all mbedtls dependencies.
> feat: disabled documentation warning when compiling with AppleClang

- protobuf/protoc_echo_plugin/EchoObjects.cpp
- When re-using a proto message in a repeated format with an array size, then the encapsulating message maxMessageSize is calculated incorrectly. 
"+" Was missed causing the calculated size to be reset
> fix: repeated proto message incorrect maxMessageSize calculation

- osal/threadx/Osal.cpp
User applications may have defined this function and expect it to be used.
> chore: make tx_application_define a weak definition

- upgrade/pack_builder/InputElf.cpp
- upgrade/pack_builder/InputHex.cpp
When adding hex and elf to upgrade pack using upgrade pack builder, pad 0xff for gap instead of 0.
> fix: pad 0xff when add hex and elf to upgrade pack

- cmake/emil_clang_tools.cmake
Allow using a custom clang-format file instead of using the one provided by the infra library.
> feat: add custom clang-format file support

- infra/util/CMakeLists.txt
- infra/util/SharedOptional.cpp
- infra/util/SharedOptional.hpp
- infra/util/test/TestSharedOptional.cpp
New overload allows for immediately notifying when the SharedOptional is already allocatable
> feat: add NotifyingSharedOptional::OnAllocatable overload

- hal/unix/UartUnix.cpp
Due to threading, object might be in destruction while running is true
> fix: UartUnix receiveData callback being called after destruction

- cmake/version.h.in
String literals are available at compile time.
This way it is possible for the compiler/linker to place them in a known location for version retrieval of a boot-loader or other applications in the flash memory
> feat: Generate string literals

- services/network_instantiations/ConnectionBsd.cpp
- services/network_instantiations/ConnectionWin.cpp
Due to recent changes on infra::BoundedDeque, an empty container is not necessary at offset zero.
As the begin() keeps moving inside internal storage, a packet could be sliced in chunks smaller than MTU size.
> fix: tcp packet fragmentation

- hal/interfaces/I2c.cpp
- hal/interfaces/I2c.hpp
A constexpr constructor allows the following:
```cpp
static constexpr hal::I2cAddress AssignedSmartBatteryAddress{0x0B << 1};
```
> feat: Make I2cAddress constexpr

- external/crypto/mbedtls/mbedtls_emil_config.h
Next to the already supported SHA256 algorithm, it is also common to sign certificates based on SHA384 and SHA512. These algorithms were not yet enabled. As a result, certificate validation would fail when any of the certificates in the chain was signed based on one of these hash algorithms. 
Enabling these algorithms as I am running into these issues right now. Since we are only enabling new features, this change is not expected to break existing functionality.
> feat: enable SHA384 and SHA512 on mbedtls

- services/network/HttpClientImpl.cpp
- services/network/HttpClientImpl.hpp
- services/network/TracingHttpClientImpl.cpp
- services/network/TracingHttpClientImpl.hpp
This also fixes crashes when data is consumed asyncronously and TracingHttpClient* is being used to trace the body of the response
> feat: refactor BodyReader handling in HttpClient implementations

- infra/util/BoundedString.hpp
- infra/util/test/TestBoundedString.cpp
The standard library's `std::string::copy` has the following behaviour:
```
Copies a substring [pos, pos + count) to character string pointed to by dest.
If the requested substring lasts past the end of the string, or if count == npos,
the copied substring is [pos, size()).
```
The current behaviour of `BoundedString::copy` is to error when `pos+count > length` which is different from the standard string copy behaviour.
This change aligns `BoundedString::copy` with the above behaviour.
> feat: changed `BoundedString::copy` to copy up to `length-pos` characters

- infra/util/BoundedString.hpp
All other `Bounded` classes really_assert on modifying methods that either under or overflow. `BoundedString` only had a normal assert, which is optimized away from all but Debug builds by default. This could result in actual buffer overflows and underflows destroying neighbouring memory.
This change aligns the `BoundedString` over/underflow behaviour with the other `Bounded` classes.
> feat: replaced assert with really_assert to align `BoundedString` overflow behaviour with other `Bounded` classes

- hal/interfaces/Can.cpp
- hal/interfaces/Can.hpp
- hal/interfaces/test/TestCan.cpp
This PR makes `hal::Can::Id` creation constexpr and adds defaulted equality operators.
C++ 20 is enabled to make use of default equality operators and is already enabled in `amp-hal-st`.
> feat: improve hal::Can::Id

- osal/threadx/CMakeLists.txt
This will bump the minimum required cmake version and solve configuration issue with the new amp-devcontainer containing cmake 4.0.0.
> chore: bump threadx to v6.4.2

- hal/unix/UartUnix.cpp
- hal/unix/UartUnix.hpp
- Established partial locks in Read()
- Reset receivedData on destruction
> fix: when UartUnix is destroyed receivedData is still called on read thread

- protobuf/echo/Echo.cpp
- services/util/test/TestEchoOnSesame.cpp
This change fixes an issue in EchoOnStreams when a new request to send is issued while a previous request is cancelled while the StreamAvailable has not been called yet.
What was happening in detail: (the **bold** part indicates where the error occurs)
- A proxy does a RequestSend
- The proxy is pushed on the sendRequesters queue
- TryGrandSend checks if sendingProxy is null (it is) and the sendRequesters queue is empty (it isn't)
- the front of the sendRequesters is assigned to sendingProxy and a request for send stream is send
- The proxy is destroyed, before the send stream is returned via SendStreamAvailable
- This cancels the request via CancelRequestSend
- The sendingProxy is not in the queue, so it must be the current serviceProxy
- sendingProxy is set to nullptr
- skipNextStream …
> fix: fixed race condition in EchoOnStreams

- infra/util/BoundedDeque.hpp
- infra/util/test/TestBoundedDeque.cpp
std::deque defines its iterator as a form of `LegacyForwardIterator` which needs to be default constructable.
In the effort of using `BoundedDeque` with the same semantics as std::deque it is required to enable the default constructor of its iterator.
> refactor: enable default constructor for BoundedDequeIterator

- lwip/lwip_cpp/LightweightIp.cpp
The `ExtCallback` will be called when the `LightweightIpOverEthernetFactory` is being created and `netif_add()` is called. `netif_default` interface will be `nullptr` at this point in time.
Add this check to avoid `nullptr` access.
> fix: add nullptr check for netif_default in LightweightIp ExtCallback

- lwip/lwip_cpp/ConnectionLwIp.hpp
The constructor needs a `BoundedList<ConnectorLwIp>`.
> fix: wrong type in ConnectionFactoryLwIp WithFixedAllocator

- services/ble/Gap.cpp
- services/ble/Gap.hpp
- services/ble/test/TestGapAdvertisementFormatter.cpp
- services/ble/test/TestGapCentral.cpp
Extend the GapAdvertisingDataFormatter with the option to add the appearance value.
> feat: extend the ble gap advertisement formatter with the option to add the appearance value

- .github/workflows/static-analysis.yml
Escaping is required to match `std::abort()` correctly
> ci: exclude std::abort from code coverage correctly
